version: '3.4'

services: 
  db:
    image: postgres
    profiles:
      - identity
      - db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres

  identity_server:
    image: identity_server
    profiles:
      - identity
    links:
      - db
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: identity_server
    healthcheck:
      test: curl -sS http://localhost/healthz || echo 1
      interval: 5s
      timeout: 10s
      retries: 3
  
  proxy:
    image: nginx:alpine
    profiles:
      - identity
    links:
      - identity_server
    volumes:
      - ./proxy_server/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy_server/cert.key:/etc/nginx/cert.key
      - ./proxy_server/cert.crt:/etc/nginx/cert.crt
    ports:
      - 443:443