version: '3.4'

services: 
  db:
    image: postgres
    profiles:
      - identity
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres

  identity_server:
    image: identity_server
    profiles:
      - identity
    links:
      - db
    depends_on:
      - db
    build:
      dockerfile: identity_server/Dockerfile
      context: identity_server/MyNotes.Identity
  
  proxy:
    image: nginx:alpine
    profiles:
      - identity
    links:
      - identity_server
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/cert.key:/etc/nginx/cert.key
      - ./.nginx/cert.crt:/etc/nginx/cert.crt
    ports:
      - 5010:5010